In [2]:
import seaborn as sns
import pandas as pd
import numpy as np
import optuna
import matplotlib.pyplot as plt
from sklearn import datasets
import missingno as msno

c:\Users\USUARIO\Downloads\Problema-de-regresi-n\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = pd.read_csv('used_cars.csv')

In [4]:
df ['price'] = df['price'].str.replace('$', '')

In [5]:
df ['price'] = df['price'].str.replace(',', '')

In [6]:
df['price'] = df['price'].astype(float)

In [7]:
df ['milage'] = df['milage'].str.replace('mi.', '')

In [8]:
df = df.drop('clean_title', axis=1)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   object
 4   fuel_type     3839 non-null   object
 5   engine        4009 non-null   object
 6   transmission  4009 non-null   object
 7   ext_col       4009 non-null   object
 8   int_col       4009 non-null   object
 9   accident      3896 non-null   object
 10  price         4009 non-null   float64
dtypes: float64(1), int64(1), object(9)
memory usage: 344.7+ KB

In [10]:
df.isna().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
price             0
dtype: int64

In [11]:
df['accident'].fillna('None Reported', inplace=True)

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_3476\1815442824.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['accident'].fillna('None Reported', inplace=True)

In [12]:
df = df.dropna(subset=['fuel_type'])

In [13]:
df ['fuel_type'] = df['fuel_type'].str.replace('–', '')

In [14]:
df ['engine'] = df['engine'].str.replace('–', '')

In [15]:
df.dropna(inplace=True)

In [16]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,10300.0
1,Hyundai,Palisade SEL,2021,"34,742",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,38005.0
2,Lexus,RX 350 RX 350,2022,"22,372",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,54598.0
3,INFINITI,Q50 Hybrid Sport,2015,"88,900",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,15500.0
4,Audi,Q3 45 S line Premium Plus,2021,"9,835",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,34999.0

In [17]:
df ['accident'] = df['accident'].str.replace('None reported', 'None Reported')

In [19]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,10300.0
1,Hyundai,Palisade SEL,2021,"34,742",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,38005.0
2,Lexus,RX 350 RX 350,2022,"22,372",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None Reported,54598.0
3,INFINITI,Q50 Hybrid Sport,2015,"88,900",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None Reported,15500.0
4,Audi,Q3 45 S line Premium Plus,2021,"9,835",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None Reported,34999.0

In [18]:
df.to_csv("data/clean_data.csv", index=False)