In [1]:
import pandas as pd

df = pd.read_csv("data/clean_data.csv")

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3437 entries, 0 to 3436
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          3437 non-null   object
 1   model          3437 non-null   object
 2   model_year     3437 non-null   int64
 3   milage         3437 non-null   float64
 4   fuel_type      3399 non-null   object
 5   engine         3399 non-null   object
 6   transmission   3437 non-null   object
 7   ext_col        3437 non-null   object
 8   int_col        3437 non-null   object
 9   accident       3437 non-null   object
 10  price          3437 non-null   float64
 11  engine_liters  3437 non-null   float64
 12  cylinders      3437 non-null   float64
 13  turbo          3437 non-null   bool
 14  horsepower     3437 non-null   int64
dtypes: bool(1), float64(4), int64(2), object(8)
memory usage: 379.4+ KB

In [3]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price,engine_liters,cylinders,turbo,horsepower
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,10300.0,3.7,6.0,False,300
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,38005.0,3.8,6.0,False,-1
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,54598.0,3.5,-1.0,False,-1
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,15500.0,3.5,6.0,False,354
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,34999.0,2.0,-1.0,True,-1

In [4]:
from sklearn.preprocessing import LabelEncoder

# Aplicar Label Encoding a fuel type
label_encoder = LabelEncoder()
df['fuel_type_label'] = label_encoder.fit_transform(df['fuel_type'])
# Mostrar cómo se asignaron los valores
print("\nAsignación de valores en Label Encoding:")
for clase, valor in zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)):
    print(f"{clase}: {valor}")

Asignación de valores en Label Encoding:
Diesel: 0
E85 Flex Fuel: 1
Gasoline: 2
Hybrid: 3
Plug-In Hybrid: 4
not supported: 5
nan: 6

In [5]:
# Aplicar Label Encoding a brand
label_encoder = LabelEncoder()
df['brand_label'] = label_encoder.fit_transform(df['brand'])
# Mostrar cómo se asignaron los valores
print("\nAsignación de valores en Label Encoding:")
for clase, valor in zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)):
    print(f"{clase}: {valor}")

Asignación de valores en Label Encoding:
Acura: 0
Alfa: 1
Aston: 2
Audi: 3
BMW: 4
Bentley: 5
Buick: 6
Cadillac: 7
Chevrolet: 8
Chrysler: 9
Dodge: 10
FIAT: 11
Ford: 12
GMC: 13
Genesis: 14
Honda: 15
Hummer: 16
Hyundai: 17
INFINITI: 18
Jaguar: 19
Jeep: 20
Kia: 21
Land: 22
Lexus: 23
Lincoln: 24
Lotus: 25
MINI: 26
Maserati: 27
Maybach: 28
Mazda: 29
Mercedes-Benz: 30
Mercury: 31
Mitsubishi: 32
Nissan: 33
Plymouth: 34
Pontiac: 35
Porsche: 36
RAM: 37
Rolls-Royce: 38
Saab: 39
Saturn: 40
Scion: 41
Subaru: 42
Toyota: 43
Volkswagen: 44
Volvo: 45
smart: 46

In [6]:
# Aplicar Label Encoding a ext_color
label_encoder = LabelEncoder()
df['ext_col_label'] = label_encoder.fit_transform(df['ext_col'])
# Mostrar cómo se asignaron los valores
print("\nAsignación de valores en Label Encoding:")
for clase, valor in zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)):
    print(f"{clase}: {valor}")

Asignación de valores en Label Encoding:
Agate Black Metallic: 0
Alfa White: 1
Alpine White: 2
Alta White: 3
Anodized Blue Metallic: 4
Anthracite Blue Metallic: 5
Antimatter Blue Metallic: 6
Apex Blue: 7
Arctic Gray Metallic: 8
Arctic White: 9
Atomic Silver: 10
Aurora Black: 11
BLACK: 12
BLUE: 13
Baltic Gray: 14
Barcelona Red: 15
Beige: 16
Billet Clearcoat Metallic: 17
Billet Silver Metallic Clearcoat: 18
Black: 19
Black Cherry: 20
Black Clearcoat: 21
Black Forest Green: 22
Black Noir Pearl: 23
Black Obsidian: 24
Black Raven: 25
Black Sapphire Metallic: 26
Blu: 27
Blue: 28
Blue Reflex Mica: 29
Blueprint: 30
Brands Hatch Gray Metallic: 31
Bright White Clearcoat: 32
Brilliant Black: 33
Brilliant Silver Metallic: 34
Bronze Dune Metallic: 35
Brown: 36
Burnished Bronze Metallic: 37
Cajun Red Tintcoat: 38
Carbon Black Metallic: 39
Carbonized Gray Metallic: 40
Carpathian Grey Premium Metallic: 41
Carrara White Metallic: 42
Caspian Blue: 43
Caviar: 44
Cayenne Red Tintcoat: 45
Chalk: 46
Chronos Gray: 47
Chronos Gray Metallic: 48
Cirrus Silver Metallic: 49
Cobra Beige Metallic: 50
Crimson Red Tintcoat: 51
Crystal Black: 52
Crystal Black Pearl: 53
Crystal Black Silica: 54
Crystal White Pearl: 55
DB Black Clearcoat: 56
Dark Ash Metallic: 57
Dark Graphite Metallic: 58
Dark Matter Metallic: 59
Dark Moon Blue Metallic: 60
Dark Moss: 61
Dark Slate Metallic: 62
Daytona Gray: 63
Daytona Gray Pearl Effect: 64
Dazzling White: 65
Deep Black Pearl Effect: 66
Deep Crystal Blue Mica: 67
Delmonico Red Pearlcoat: 68
Diamond Black: 69
Donington Grey Metallic: 70
Ebony Black: 71
Ebony Twilight Metallic: 72
Eiger Grey: 73
Eiger Grey Metallic: 74
Electric Blue Metallic: 75
Ember Pearlcoat: 76
Emerald Green Metallic: 77
Emin White: 78
Eminent White Pearl: 79
Firecracker Red Clearcoat: 80
Firenze Red: 81
Firenze Red Metallic: 82
Flame Red Clearcoat: 83
Florett Silver: 84
Frozen White: 85
Fuji White: 86
Garnet Red Metallic: 87
Gecko Pearlcoat: 88
Glacial White Pearl: 89
Glacier Blue Metallic: 90
Glacier White: 91
Glacier White Metallic: 92
Go Mango!: 93
Gold: 94
Granite Crystal Clearcoat Metallic: 95
Granite Crystal Metallic Clearcoat: 96
Graphite Grey: 97
Graphite Grey Metallic: 98
Gray: 99
Green: 100
Gun Metallic: 101
Hampton Gray: 102
Hellayella Clearcoat: 103
Horizon Blue: 104
Hydro Blue Pearlcoat: 105
Hyper Red: 106
Ibis White: 107
Ice Silver Metallic: 108
Iconic Silver Metallic: 109
Imperial Blue Metallic: 110
Indus Silver: 111
Ingot Silver Metallic: 112
Iridescent Pearl Tricoat: 113
Iridium Metallic: 114
Ironman Silver: 115
Isle of Man Green Metallic: 116
Jet Black Mica: 117
Jungle Green: 118
Jupiter Red: 119
Kinetic Blue: 120
Kodiak Brown Metallic: 121
Liquid Platinum: 122
Lunar Blue Metallic: 123
Lunar Silver Metallic: 124
Lunare White Metallic: 125
MANUFAKTUR Diamond White Bright: 126
Machine Gray Metallic: 127
Magnetic Black: 128
Magnetic Gray Clearcoat: 129
Magnetic Gray Metallic: 130
Magnetic Metallic: 131
Magnetite Gray Metallic: 132
Majestic Black Pearl: 133
Majestic Plum Metallic: 134
Mango Tango Pearlcoat: 135
Manhattan Noir Metallic: 136
Maroon: 137
Matador Red Metallic: 138
Matador Red Mica: 139
Maximum Steel Metallic: 140
Metallic: 141
Midnight Black: 142
Midnight Black Metallic: 143
Midnight Blue Metallic: 144
Mineral White: 145
Moonlight Cloud: 146
Mosaic Black Metallic: 147
Mountain Air Metallic: 148
Mythos Black: 149
Mythos Black Metallic: 150
Nautical Blue Pearl: 151
Navarra Blue: 152
Navarre Blue: 153
Nebula Gray Pearl: 154
Northsky Blue Metallic: 155
Obsidian: 156
Obsidian Black Metallic: 157
Octane Red Pearlcoat: 158
Onyx Black: 159
Orange: 160
Orca Black Metallic: 161
Oryx White Prl: 162
Oxford White: 163
Pacific Blue: 164
Pacific Blue Metallic: 165
Passion Red: 166
Patriot Blue Pearlcoat: 167
Pearl White: 168
Phantom Black: 169
Phantom Black Pearl Effect / Black Roof: 170
Phytonic Blue Metallic: 171
Pink: 172
Platinum Gray Metallic: 173
Platinum Quartz Metallic: 174
Platinum White Pearl: 175
Polymetal Gray Metallic: 176
Portofino Blue Metallic: 177
Portofino Gray: 178
Pristine White: 179
Pure White: 180
Purple: 181
Quartz Blue Pearl: 182
Quartz White: 183
Quicksilver Metallic: 184
Radiant Red Metallic II: 185
Rapid Red Metallic Tinted Clearcoat: 186
Red: 187
Red Obsession: 188
Red Quartz Tintcoat: 189
Redline Red: 190
Rich Garnet Metallic: 191
Rosso: 192
Ruby Flare Pearl: 193
Ruby Red Metallic Tinted Clearcoat: 194
Sandstone Metallic: 195
Sangria Red: 196
Santorin Black: 197
Santorini Black: 198
Santorini Black Metallic: 199
Satin Steel Metallic: 200
Scarlet Ember: 201
Selenite Gray Metallic: 202
Selenite Grey Metallic: 203
Shadow Black: 204
Shadow Gray Metallic: 205
Shimmering Silver: 206
Shoreline Blue Pearl: 207
Silky Silver: 208
Silver: 209
Silver Flare Metallic: 210
Silver Ice Metallic: 211
Silver Mist: 212
Silver Radiance: 213
Silver Zynith: 214
Siren Red Tintcoat: 215
Snow White Pearl: 216
Snowflake White Pearl: 217
Snowflake White Pearl Metallic: 218
Sonic Silver Metallic: 219
Soul Red Crystal Metallic: 220
Sparkling Silver: 221
Stellar Black Metallic: 222
Sting Gray Clearcoat: 223
Stone Gray Metallic: 224
Stormy Sea: 225
Summit White: 226
Sunset Drift Chromaflair: 227
Super Black: 228
Super White: 229
Tan: 230
Tango Red Metallic: 231
Titanium Silver: 232
Tungsten Metallic: 233
Twilight Black: 234
Twilight Blue Metallic: 235
Typhoon Gray: 236
Ultra Black: 237
Ultra White: 238
Velvet Red Pearlcoat: 239
Verde: 240
Vik Black: 241
Volcanic Orange: 242
Volcano Grey Metallic: 243
Vulcano Black Metallic: 244
White: 245
White Clearcoat: 246
White Diamond Tri-Coat: 247
White Frost Tri-Coat: 248
White Knuckle Clearcoat: 249
White Platinum Tri-Coat Metallic: 250
Wind Chill Pearl: 251
Wolf Gray: 252
Yellow: 253
Yulong: 254
Yulong White: 255
designo Diamond White: 256
designo Diamond White Bright: 257
designo Diamond White Metallic: 258
–: 259

In [7]:
# Aplicar Label Encoding a int_color
label_encoder = LabelEncoder()
df['int_col_label'] = label_encoder.fit_transform(df['int_col'])
# Mostrar cómo se asignaron los valores
print("\nAsignación de valores en Label Encoding:")
for clase, valor in zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)):
    print(f"{clase}: {valor}")

Asignación de valores en Label Encoding:
AMG Black: 0
Adrenaline Red: 1
Almond Beige: 2
Amber: 3
Anthracite: 4
Aragon Brown: 5
Ash: 6
BLACK: 7
Beige: 8
Black: 9
Black / Gray: 10
Black / Saddle: 11
Black / Stone Grey: 12
Black Onyx: 13
Black w/Red Stitching: 14
Black/Graphite: 15
Black/Gun Metal: 16
Black/Saddle Brown: 17
Blk: 18
Blue: 19
Boulder: 20
Brown: 21
Camel: 22
Camel Leather: 23
Canberra Beige: 24
Canberra Beige/Black: 25
Cappuccino: 26
Carbon Black: 27
Ceramic: 28
Charcoal: 29
Charcoal Black: 30
Chateau: 31
Chestnut: 32
Classic Red: 33
Cloud: 34
Cocoa / Dune: 35
Dark Ash: 36
Dark Auburn: 37
Dark Galvanized: 38
Dark Gray: 39
Deep Cypress: 40
Diesel Gray / Black: 41
Ebony: 42
Ebony / Ebony Accents: 43
Ebony / Pimento: 44
Ebony Black: 45
Ebony.: 46
Ebony/Light Oyster Stitch: 47
Espresso: 48
Gideon: 49
Global Black: 50
Gold: 51
Graphite: 52
Graphite w/Gun Metal: 53
Gray: 54
Graystone: 55
Green: 56
Ice: 57
Ivory / Ebony: 58
Jet Black: 59
Kyalami Orange: 60
Light Gray: 61
Light Platinum / Jet Black: 62
Light Slate: 63
Light Titanium: 64
Macchiato: 65
Macchiato Beige/Black: 66
Macchiato/Magmagrey: 67
Magma Red: 68
Medium Ash Gray: 69
Medium Dark Slate: 70
Medium Earth Gray: 71
Medium Light Camel: 72
Medium Pewter: 73
Medium Stone: 74
Mesa: 75
Mistral Gray / Raven: 76
Mocha: 77
Mountain Brown: 78
Navy Pier: 79
Nero: 80
Nougat Brown: 81
ORANGE: 82
Obsidian Black: 83
Orange: 84
Orchid: 85
Oyster W/Contrast: 86
Oyster/Black: 87
Parchment: 88
Parchment.: 89
Pearl Beige: 90
Pimento / Ebony: 91
Pimento Red w/Ebony: 92
Platinum: 93
Red: 94
Red / Black: 95
Red/Black: 96
Rhapsody Blue: 97
Rioja Red: 98
Roast: 99
Rock Gray: 100
Saddle Brown: 101
Saiga Beige: 102
Sand Beige: 103
Sandstone: 104
Sarder Brown: 105
Satin Black: 106
Shale: 107
Shara Beige: 108
Silk Beige/Black: 109
Silk Beige/Espresso Brown: 110
Silver: 111
Slate: 112
Sport: 113
Tan: 114
Tan/Ebony: 115
Tan/Ebony/Ebony: 116
Tension: 117
Titan Black: 118
Titan Black / Quarzit: 119
Tupelo: 120
Very Light Cashmere: 121
WHITE: 122
Walnut: 123
Whisper Beige: 124
White: 125
White / Brown: 126
Yellow: 127
–: 128

In [8]:
# Aplicar Label Encoding a model
label_encoder = LabelEncoder()
df['model_label'] = label_encoder.fit_transform(df['model'])
# Mostrar cómo se asignaron los valores
print("\nAsignación de valores en Label Encoding:")
for clase, valor in zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)):
    print(f"{clase}: {valor}")

Asignación de valores en Label Encoding:
124 Spider Abarth: 0
128 i: 1
135 i: 2
135 is: 3
1500 Big Horn: 4
1500 Cheyenne: 5
1500 Cheyenne Extended Cab: 6
1500 Classic SLT: 7
1500 Classic Tradesman: 8
1500 Classic Warlock: 9
1500 Laramie: 10
1500 Limited: 11
1500 Longhorn: 12
1500 Rebel: 13
1500 SLT: 14
1500 Sport: 15
1500 TRX: 16
1500 Tradesman/Express: 17
200 C: 18
200 Limited: 19
228 Gran Coupe i xDrive: 20
228 i: 21
230 i: 22
240SX Base: 23
2500 Big Horn: 24
2500 Laramie: 25
2500 Longhorn: 26
2500 SLT: 27
2500 Tradesman: 28
300 Base: 29
300 S: 30
300 Touring: 31
300C Base: 32
300C SRT8: 33
300M Base: 34
300ZX Base: 35
320 i xDrive: 36
323 Ci: 37
325 Ci: 38
325 i: 39
325 xi: 40
328 i: 41
328 i xDrive: 42
328 xi: 43
330 330i xDrive: 44
330 i: 45
330 i xDrive: 46
330e iPerformance: 47
335 i: 48
335 i xDrive: 49
335 is: 50
340 i: 51
3500 Laramie: 52
3500 SLT: 53
3500 Tradesman: 54
350Z Enthusiast: 55
350Z NISMO: 56
350Z Touring: 57
370Z Base: 58
370Z NISMO: 59
370Z NISMO Tech: 60
370Z Touring: 61
428 Gran Coupe i xDrive: 62
428 i: 63
428 i xDrive: 64
428 i xDrive SULEV: 65
430 430i: 66
430 Gran Coupe i xDrive: 67
430 i: 68
430 i xDrive: 69
435 Gran Coupe i: 70
435 i: 71
435 i xDrive: 72
440 Gran Coupe 440i xDrive: 73
440 Gran Coupe i: 74
440 i xDrive: 75
4Runner 4WD: 76
4Runner Limited: 77
4Runner Limited Nightshade: 78
4Runner SR5: 79
4Runner SR5 Premium: 80
4Runner TRD Off Road: 81
4Runner TRD Pro: 82
4Runner Trail: 83
4Runner Venture Special Edition: 84
500 Lounge: 85
500 Sport: 86
500X Trekking Plus: 87
525 i: 88
528 i: 89
528 i xDrive: 90
530 i: 91
530 i xDrive: 92
530e Base: 93
535 i: 94
535 i xDrive: 95
540 i: 96
540 i xDrive: 97
550 Gran Turismo i: 98
550 i xDrive: 99
640 Gran Coupe i: 100
640 Gran Coupe i xDrive: 101
640 i: 102
650 Gran Coupe i: 103
650 Gran Coupe i xDrive: 104
650 i: 105
650 i xDrive: 106
718 Boxster Base: 107
718 Boxster S: 108
718 Cayman GTS: 109
718 Cayman S: 110
740 Li: 111
740 i: 112
740 iL: 113
740e xDrive iPerformance: 114
750 750i xDrive: 115
750 Li: 116
750 Li xDrive: 117
750 i: 118
750 i xDrive: 119
750 iL: 120
840 Gran Coupe i xDrive: 121
840 i xDrive: 122
850 Turbo: 123
86 860 Special Edition: 124
86 Base: 125
9-3 Aero: 126
9-3 SE: 127
911 Carrera: 128
911 Carrera 4: 129
911 Carrera 4 Cabriolet: 130
911 Carrera 4S: 131
911 Carrera 4S Cabriolet: 132
911 Carrera C2S: 133
911 Carrera C4S: 134
911 Carrera Cabriolet: 135
911 Carrera S: 136
911 Carrera S Cabriolet: 137
911 Carrera Turbo: 138
911 Turbo: 139
911 Turbo Cabriolet: 140
A-Class A 220 4MATIC: 141
A3 2.0 TDI Premium Plus: 142
A3 2.0T: 143
A3 2.0T Premium: 144
A3 2.0T Tech Premium: 145
A4 2.0T Premium: 146
A4 2.0T Premium Plus: 147
A4 2.0T Premium Plus quattro: 148
A4 2.0T Premium quattro: 149
A4 2.0T Tech Premium: 150
A4 2.0T Titanium Premium: 151
A4 3.2 Premium Plus quattro: 152
A5 2.0T Premium: 153
A5 2.0T Premium Plus: 154
A5 2.0T Prestige: 155
A5 45 S line Premium Plus: 156
A5 Sportback S line Premium Plus: 157
A6 2.0T Premium Plus: 158
A6 3.0 TDI Premium Plus: 159
A6 3.0T Premium Plus: 160
A6 3.0T Prestige: 161
A6 3.2 quattro: 162
A6 45 Premium Plus: 163
A6 55 Premium: 164
A6 55 Premium Plus: 165
A6 55 Prestige: 166
A7 3.0T Premium: 167
A7 3.0T Premium Plus: 168
A7 3.0T Prestige: 169
A7 55 Premium: 170
A7 55 Premium Plus: 171
A7 Premium: 172
A7 Premium Plus: 173
A8 4.0: 174
A8 4.0T: 175
A8 L 3.0T: 176
A8 L 4.0T: 177
A8 L 55: 178
ALPINA B7 ALPINA B7 xDrive: 179
ALPINA B7 Base: 180
ALPINA B7 xDrive: 181
AMG C 43 AMG C 43 4MATIC: 182
AMG C 43 Base: 183
AMG C 43 Base 4MATIC: 184
AMG C 63 Base: 185
AMG C 63 S: 186
AMG C AMG C 63: 187
AMG C AMG C 63 S: 188
AMG CLA 45 Base 4MATIC: 189
AMG E 53 4MATIC: 190
AMG E 53 Base 4MATIC: 191
AMG E 63 S 4MATIC: 192
AMG G 63 Base: 193
AMG G AMG G 63 4MATIC: 194
AMG GL AMG GL 63 4MATIC: 195
AMG GLA 45 Base 4MATIC: 196
AMG GLC 43 AMG GLC 43: 197
AMG GLC 63 Base 4MATIC: 198
AMG GLE 43 4MATIC Coupe: 199
AMG GLE 43 Coupe 4MATIC: 200
AMG GLE 53 AMG GLE 53: 201
AMG GLE 63 S Coupe 4MATIC: 202
AMG GLE AMG GLE 63 S-Model 4MATIC: 203
AMG GT 53 Base: 204
AMG GT AMG GT: 205
AMG GT AMG GT S: 206
AMG GT Base: 207
AMG S 63 Base 4MATIC: 208
ATS 2.0L Turbo: 209
ATS 2.0L Turbo Luxury: 210
ATS 2.5L: 211
ATS 2.5L Luxury: 212
ATS 3.6L Luxury: 213
Acadia Denali: 214
Acadia SLE: 215
Acadia SLE-1: 216
Acadia SLE-2: 217
Acadia SLT-1: 218
Acadia SLT-2: 219
Accent GL: 220
Accent GLS: 221
Accent SEL: 222
Accord Crosstour EX-L: 223
Accord EX-L: 224
Accord EX-L 2.0T: 225
Accord Hybrid Base: 226
Accord Hybrid Touring: 227
Accord Sport: 228
Altima 2.5 S: 229
Altima 2.5 SL: 230
Altima 2.5 SV: 231
Armada LE: 232
Armada Platinum: 233
Armada SL: 234
Armada SV: 235
Arnage R: 236
Arteon 2.0T SE: 237
Arteon 2.0T SEL Premium R-Line: 238
Arteon 2.0T SEL R-Line: 239
Arteon SEL R-Line: 240
Ascent Limited 7-Passenger: 241
Ascent Touring 7-Passenger: 242
Atlas 3.6L SEL Premium: 243
Atlas 3.6L SEL Premium R-Line: 244
Atlas Cross Sport 3.6L V6 SEL Premium: 245
Avalanche 1500 LS: 246
Avalanche 1500 LT: 247
Avalanche 1500 LTZ: 248
Avalanche LTZ: 249
Avalon Hybrid XLE Premium: 250
Avalon Limited: 251
Avalon Touring: 252
Avalon XLE: 253
Avalon XLS: 254
Avenger SE: 255
Aviator Luxury: 256
Aviator Reserve AWD: 257
BRZ Limited: 258
BRZ Premium: 259
Baja Base: 260
Beetle 1.8T: 261
Beetle 2.0T S: 262
Blazer Premier: 263
Boxster Base: 264
Boxster Black Edition: 265
Boxster GTS: 266
Boxster RS 60 Spyder: 267
Boxster S: 268
Bronco: 269
Bronco Badlands: 270
Bronco Badlands Advanced: 271
Bronco Base: 272
Bronco Big Bend: 273
Bronco Big Bend Advanced: 274
Bronco Heritage Edition Advanced: 275
Bronco Outer Banks: 276
Bronco Outer Banks Advanced: 277
Bronco Sport Base: 278
Bronco Sport Big Bend: 279
Bronco Sport Outer Banks: 280
Bronco Wildtrak Advanced: 281
Bronco XLT: 282
C-Class 4MATIC Sedan: 283
C-Class C 250 Luxury: 284
C-Class C 250 Sport: 285
C-Class C 300: 286
C-Class C 300 4MATIC: 287
C-Class C 300 4MATIC Luxury: 288
C-Class C 300 4MATIC Sport: 289
C-Class C 300 Luxury: 290
C-Class C 63 AMG: 291
C-Class C280 4MATIC: 292
C-Class C300 4MATIC: 293
C-Class C55 AMG Sport: 294
C-HR LE: 295
C-Max Energi SE: 296
C30 T5 Premier Plus: 297
C70 T5: 298
CC 2.0T Sport: 299
CC Sport: 300
CLA-Class CLA 250: 301
CLK-Class 500 Cabriolet: 302
CLK-Class 550: 303
CLK-Class CLK 350: 304
CLS 450 Base: 305
CLS-Class CLS 400 4MATIC: 306
CLS-Class CLS 550: 307
CLS-Class CLS 63 AMG S-Model 4MATIC: 308
CLS-Class CLS500: 309
CR-V EX: 310
CR-V EX-L: 311
CR-V LX: 312
CR-V Touring: 313
CT 200h Premium: 314
CT4 Luxury: 315
CT5 Premium Luxury: 316
CT5-V V-Series: 317
CT6 Luxury: 318
CT6-V 4.2L Blackwing Twin Turbo: 319
CTS 2.0L Turbo Luxury: 320
CTS 3.6L Luxury: 321
CTS 3.6L Premium: 322
CTS 3.6L Premium Luxury: 323
CTS Base: 324
CTS Luxury: 325
CTS Performance: 326
CTS Premium: 327
CTS-V Base: 328
CX-30 2.5 S Select Package: 329
CX-30 Base: 330
CX-30 Preferred: 331
CX-30 Premium Package: 332
CX-30 Select: 333
CX-5 Grand Touring: 334
CX-5 Touring: 335
CX-50 2.5 Turbo Premium Package: 336
CX-7 Grand Touring: 337
CX-7 Sport: 338
CX-9 Carbon Edition: 339
CX-9 Grand Touring: 340
CX-9 Signature: 341
CX-9 Touring: 342
CX-9 Touring Plus: 343
CX-90 Premium: 344
Caliber Express: 345
Camaro 1LT: 346
Camaro 1SS: 347
Camaro 2LT: 348
Camaro 2SS: 349
Camaro Base: 350
Camaro LT1: 351
Camaro Z28: 352
Camaro ZL1: 353
Camry Hybrid Base: 354
Camry Hybrid LE: 355
Camry Hybrid XLE: 356
Camry LE: 357
Camry SE: 358
Camry Solara SE: 359
Camry Solara SLE: 360
Camry Solara SLE V6: 361
Camry XLE: 362
Camry XSE: 363
Canyon Elevation Standard: 364
Capri XR2: 365
Caprice Classic Base: 366
Cayenne AWD: 367
Cayenne Base: 368
Cayenne Diesel: 369
Cayenne E-Hybrid S: 370
Cayenne E-Hybrid S Platinum Edition: 371
Cayenne GTS: 372
Cayenne Platinum Edition: 373
Cayenne S: 374
Cayenne Turbo: 375
Cayenne Turbo S: 376
Cayman Base: 377
Cayman GTS: 378
Cayman R: 379
Cayman S: 380
Celica GT: 381
Challenger GT: 382
Challenger R/T: 383
Challenger R/T Scat Pack: 384
Challenger SE: 385
Challenger SRT 392: 386
Challenger SRT Hellcat: 387
Challenger SRT8: 388
Challenger SRT8 392: 389
Challenger SXT: 390
Charger GT: 391
Charger R/T: 392
Charger R/T 392: 393
Charger R/T Scat Pack: 394
Charger SE: 395
Charger SRT Hellcat: 396
Charger SRT8: 397
Charger Scat Pack: 398
Cherokee Sport: 399
Cherokee X: 400
Civic EX: 401
Civic LX: 402
Civic Si: 403
Civic Si Base: 404
Civic Sport: 405
Civic Type R Touring: 406
Clarity Plug-In Hybrid Base: 407
Clubman Cooper S ALL4: 408
Colorado LT: 409
Colorado LT Crew Cab: 410
Colorado Z71: 411
Colorado Z85: 412
Colorado ZR2: 413
Commander Base: 414
Commander Sport: 415
Compass High Altitude: 416
Compass Latitude: 417
Compass Limited: 418
Compass Sport: 419
Compass Trailhawk: 420
Continental GT Base: 421
Continental GT Speed: 422
Continental GTC Base: 423
Continental GTC V8: 424
Continental Reserve: 425
Convertible Cooper: 426
Convertible John Cooper Works: 427
Cooper Base: 428
Cooper S Base: 429
Cooper S Clubman Base: 430
Corolla CE: 431
Corolla Hybrid LE: 432
Corolla LE: 433
Corolla S Plus: 434
Corolla iM Base: 435
Corsair Grand Touring: 436
Corsair Reserve: 437
Corsair Standard: 438
Corvette Base: 439
Corvette Grand Sport: 440
Corvette Stingray: 441
Corvette Stingray Z51: 442
Corvette Stingray w/1LT: 443
Corvette Stingray w/2LT: 444
Corvette Stingray w/3LT: 445
Corvette Z06: 446
Corvette ZR-1: 447
Countryman Cooper: 448
Countryman Cooper S: 449
Countryman Cooper S ALL4: 450
Coupe Cambiocorsa: 451
Crossfire Limited: 452
Crosstour EX-L: 453
Crosstrek 2.0i Limited: 454
Crosstrek 2.0i Premium: 455
Crosstrek Premium: 456
Cruze LS: 457
Cruze LT: 458
Cruze LT Automatic: 459
Cruze LTZ: 460
Cube 1.8 S: 461
DTS Base: 462
DTS Luxury: 463
DTS Luxury II: 464
Dakota Big Horn/Lone Star: 465
Dakota SLT: 466
Dakota SLT Quad Cab: 467
Dakota Sport: 468
Dart SE: 469
DeVille Base: 470
Durango GT: 471
Durango R/T: 472
Durango SLT: 473
Durango SRT: 474
Durango SRT 392: 475
E-Class 400E: 476
E-Class AMG E 53: 477
E-Class D 2.5 Turbo: 478
E-Class E 300: 479
E-Class E 300 4MATIC: 480
E-Class E 350: 481
E-Class E 350 4MATIC: 482
E-Class E 400: 483
E-Class E 400 4MATIC: 484
E-Class E 450 4MATIC: 485
E-Class E 550: 486
E-Class E 550 4MATIC: 487
E-Class E500: 488
E-Class E55 AMG: 489
E-PACE 300 Sport: 490
E-PACE S: 491
E150 XLT: 492
E250 Cargo: 493
E350 Super Duty Base: 494
E350 Super Duty XLT: 495
ES 250 Base: 496
ES 300h Base: 497
ES 330 Base: 498
ES 350 Base: 499
Eclipse GS: 500
Eclipse GT: 501
Eclipse Spyder GS: 502
Eclipse Spyder GT: 503
Edge SE: 504
Edge SEL: 505
Edge Sport: 506
Edge Titanium: 507
Elantra GLS: 508
Elantra N Base: 509
Elantra SE: 510
Element EX: 511
Elise Base: 512
Enclave 1XL: 513
Enclave Avenir: 514
Enclave Essence: 515
Enclave Leather: 516
Enclave Premium: 517
Encore GX Essence: 518
Encore Preferred: 519
Envision Essence: 520
Envision Preferred: 521
Eos 2.0T: 522
Equinox 2LT: 523
Equinox LT: 524
Equinox Premier w/2LZ: 525
Equus Signature: 526
Escalade ESV Base: 527
Escalade ESV Luxury: 528
Escalade ESV Platinum: 529
Escalade ESV Platinum Edition: 530
Escalade ESV Premium Luxury: 531
Escalade ESV Premium Luxury Platinum: 532
Escalade ESV Sport: 533
Escalade EXT Base: 534
Escalade Luxury: 535
Escalade Platinum: 536
Escalade Platinum Edition: 537
Escalade Premium: 538
Escalade Premium Luxury: 539
Escalade Premium Luxury Platinum: 540
Escalade Sport Platinum: 541
Escape Limited: 542
Escape SE: 543
Escape XLT: 544
Eurovan MV: 545
Evora 2+2: 546
Evora 400 Base: 547
Evora Base: 548
Excursion Limited: 549
Excursion Limited 4WD: 550
Excursion Limited Ultimate: 551
Excursion XLS: 552
Excursion XLT 4WD: 553
Expedition EL King Ranch: 554
Expedition EL Limited: 555
Expedition EL XLT: 556
Expedition King Ranch: 557
Expedition Limited: 558
Expedition Max King Ranch: 559
Expedition Max Limited: 560
Expedition Max XLT: 561
Expedition Platinum: 562
Expedition Timberline: 563
Expedition XLT: 564
Explorer Eddie Bauer: 565
Explorer Limited: 566
Explorer Platinum: 567
Explorer ST: 568
Explorer Sport: 569
Explorer Sport Trac XLT: 570
Explorer Timberline: 571
Explorer XLT: 572
Explorer sport: 573
Express 1500 Base: 574
Express 1500 Cargo: 575
Express 1500 Work Van: 576
Express 2500 Work Van: 577
Express 3500 Base: 578
Express 3500 LT: 579
F-150 FX4: 580
F-150 Heritage XL SuperCab Flareside: 581
F-150 Lariat: 582
F-150 Lariat SuperCrew: 583
F-150 Limited: 584
F-150 Platinum: 585
F-150 Raptor: 586
F-150 SVT Raptor: 587
F-150 Tremor: 588
F-150 XL: 589
F-150 XLT: 590
F-150 XLT SuperCab: 591
F-250 Base: 592
F-250 King Ranch: 593
F-250 LARIAT: 594
F-250 Lariat: 595
F-250 Limited: 596
F-250 Platinum: 597
F-250 XL: 598
F-250 XL Crew Cab Super Duty: 599
F-250 XL SuperCab H/D: 600
F-250 XLT: 601
F-250 XLT Crew Cab Super Duty: 602
F-250 XLT Super Duty: 603
F-250 XLT SuperCab Super Duty: 604
F-350 King Ranch: 605
F-350 Lariat: 606
F-350 Lariat Crew Cab Super Duty DRW: 607
F-350 Lariat Super Duty Crew Cab: 608
F-350 Platinum: 609
F-350 XL: 610
F-350 XLT: 611
F-PACE 25t Premium: 612
F-PACE 30t R-Sport: 613
F-PACE S: 614
F-PACE SVR: 615
F-TYPE: 616
F-TYPE R: 617
F-TYPE S: 618
F-TYPE S British Design Edition: 619
F-TYPE V6 S: 620
FJ Cruiser Base: 621
FR-S Monogram: 622
FX37 Base: 623
FX50 Base: 624
Fiesta ST: 625
Firebird Base: 626
Firebird Trans Am: 627
Fit Sport: 628
Flex Limited: 629
Flex SEL: 630
Focus RS Base: 631
Focus SE: 632
Focus SEL: 633
Focus ST Base: 634
ForTwo Pure: 635
Forester 2.5 X: 636
Forester 2.5 XT: 637
Forester 2.5i Limited: 638
Forester Base: 639
Forester Premium: 640
Forte GT-Line: 641
Forte Koup EX: 642
Forte LX: 643
Frontier SE Crew Cab: 644
Frontier SL: 645
Frontier SV: 646
Fusion Energi Titanium: 647
Fusion Hybrid Base: 648
Fusion Hybrid SE: 649
Fusion Hybrid SE Hybrid: 650
Fusion Hybrid Titanium: 651
Fusion SE: 652
G-Class G 550 4MATIC: 653
G-Class G 63 AMG: 654
G35 Base: 655
G35 Sport: 656
G37 Journey: 657
G37 S Sport: 658
G37 Sport: 659
G37 x: 660
G6 GTP: 661
G70 2.0T: 662
G70 3.3T: 663
G70 3.3T Advanced: 664
G8 GT: 665
G80 2.5T: 666
G80 3.3T Sport: 667
G80 3.8: 668
G90 3.3T Premium: 669
G90 5.0 Ultimate: 670
GL-Class GL 450: 671
GL-Class GL 450 4MATIC: 672
GL-Class GL 550: 673
GL-Class GL 550 4MATIC: 674
GLA 250 Base 4MATIC: 675
GLA-Class GLA 250 4MATIC: 676
GLB 250 Base 4MATIC: 677
GLC 300 Base: 678
GLC 300 Base 4MATIC: 679
GLC 300 GLC 300: 680
GLE 350 Base: 681
GLE 350 Base 4MATIC: 682
GLE 350 GLE 350: 683
GLE 450 GLE 450: 684
GLK-Class GLK 350: 685
GLS 450 Base: 686
GLS 450 Base 4MATIC: 687
GLS 550 Base 4MATIC: 688
GR Corolla Circuit Edition: 689
GR86 Base: 690
GR86 Premium: 691
GS 350 Base: 692
GS 350 F Sport: 693
GT-R Black Edition: 694
GT-R Premium: 695
GTI Base: 696
GTO Base: 697
GV70 2.5T: 698
GV70 3.5T Sport: 699
GV80 2.5T: 700
GX 460 Base: 701
GX 460 Luxury: 702
GX 460 Premium: 703
GX 470 Base: 704
Genesis 3.8: 705
Genesis 4.6: 706
Genesis 5: 707
Genesis Coupe 2.0T: 708
Genesis Coupe 2.0T R-Spec: 709
Genesis Coupe 3.8 Base: 710
Genesis Coupe 3.8 Grand Touring: 711
Genesis Coupe 3.8 R-Spec: 712
Genesis Coupe 3.8 Track: 713
Ghibli Base: 714
Ghibli S GranLusso: 715
Ghibli S Q4: 716
Ghibli S Q4 GranSport: 717
Ghost Base: 718
Gladiator Freedom: 719
Gladiator Mojave: 720
Gladiator Overland: 721
Gladiator Rubicon: 722
Gladiator Sport: 723
Gladiator Sport S: 724
Gladiator Willys: 725
Golf Auto TSI S: 726
Golf GTI 2.0T Autobahn: 727
Golf GTI 2.0T Autobahn 4-Door: 728
Golf GTI 2.0T S 4-Door: 729
Golf GTI 2.0T SE 4-Door: 730
Golf GTI 2.0T SE w/Performance Package 4-Door: 731
Golf R 20th Anniversary Edition: 732
Golf R 4-Door: 733
Golf R 4-Door w/DCC & Navigation: 734
Golf R Base: 735
Golf SportWagen TSI S 4-Door: 736
Golf SportWagen TSI SE: 737
GranTurismo Base: 738
GranTurismo MC: 739
GranTurismo Sport: 740
Grand Caravan R/T: 741
Grand Cherokee Altitude: 742
Grand Cherokee L Laredo: 743
Grand Cherokee L Limited: 744
Grand Cherokee L Overland: 745
Grand Cherokee L Summit: 746
Grand Cherokee Laredo: 747
Grand Cherokee Limited: 748
Grand Cherokee Summit: 749
Grand Cherokee WK Laredo X: 750
Grand Wagoneer Base: 751
Grand Wagoneer Series III: 752
Grecale Modena: 753
H2 Base: 754
H2 SUT: 755
H3 Base: 756
HS 250h Premium: 757
Hardtop Cooper: 758
Hardtop Cooper S: 759
Highlander Base: 760
Highlander Hybrid Limited: 761
Highlander Hybrid Limited Platinum: 762
Highlander Hybrid XLE: 763
Highlander LE Plus: 764
Highlander Limited: 765
Highlander Limited Platinum: 766
Highlander Platinum: 767
Highlander SE: 768
Highlander XLE: 769
ILX 2.0L w/Premium Package: 770
ILX 2.4L: 771
ILX Premium & A-SPEC Packages: 772
ILX Premium Package: 773
ILX Technology Plus Package: 774
IONIQ Plug-In Hybrid SEL: 775
IS 250 Base: 776
IS 250C Base: 777
IS 300 Base: 778
IS 350 Base: 779
IS 350 F Sport: 780
IS-F Base: 781
Impala 1LT: 782
Impala Base: 783
Impreza 2.0i: 784
Impreza 2.0i Premium: 785
Impreza 2.0i Sport: 786
Impreza Outback Sport Wagon: 787
Impreza Premium: 788
Impreza WRX: 789
Impreza WRX Base: 790
Impreza WRX Premium: 791
Impreza WRX STI: 792
Impreza WRX Sti: 793
Impreza WRX Sti Special Edition: 794
Insight EX: 795
Integra GS-R: 796
Integra LS: 797
Integra w/A-Spec Tech Package: 798
Jetta 1.4T R-Line: 799
Jetta 1.4T S: 800
Jetta 1.4T SE: 801
Jetta GLI: 802
Jetta GLX VR6: 803
Jetta S: 804
Jetta SportWagen SE: 805
Juke NISMO RS: 806
Juke SL: 807
Juke SV: 808
K5 EX: 809
K5 GT-Line: 810
K900 5.0L: 811
Kicks S: 812
Kona N Base: 813
LC 500 Base: 814
LS 430 Base: 815
LS 460 Base: 816
LS 460 Crafted Line: 817
LS 460 L: 818
LS 500 Base: 819
LS 500 F Sport: 820
LS V8: 821
LX 470 Base: 822
LX 570 Base: 823
LX 570 Three-Row: 824
LaCrosse Base: 825
LaCrosse CX: 826
LaCrosse Leather: 827
Lancer DE: 828
Lancer Evolution Base: 829
Lancer Evolution GSR: 830
Lancer Evolution IX: 831
Lancer Evolution MR: 832
Lancer GTS: 833
Lancer Sportback ES: 834
Land Cruiser: 835
Land Cruiser Base: 836
Legacy 2.5 GT spec.B: 837
Legacy 2.5 i Premium: 838
Legacy 2.5i Premium: 839
Levante GTS: 840
Levante Modena: 841
Levante S: 842
Liberty Limited: 843
Liberty Renegade: 844
Liberty Sport: 845
Lucerne CXL: 846
M-Class ML 350: 847
M-Class ML 350 4MATIC: 848
M2 Base: 849
M2 Competition: 850
M235 i: 851
M240 i: 852
M3 Base: 853
M3 CS: 854
M3 Competition: 855
M3 Competition xDrive: 856
M340 i xDrive: 857
M37 x: 858
M4 Base: 859
M4 CS: 860
M4 Competition: 861
M4 Competition xDrive: 862
M440 i: 863
M440 i xDrive: 864
M5 Base: 865
M5 Competition: 866
M550 i xDrive: 867
M56 Base: 868
M6 Base: 869
M6 Gran Coupe Base: 870
M760 M760i xDrive: 871
M760 i xDrive: 872
M8 Base: 873
M8 Competition: 874
M850 i xDrive: 875
MDX 3.5L Technology Package: 876
MDX 3.5L w/Advance & Entertainment Pkgs: 877
MDX 3.5L w/Technology Package: 878
MDX 3.7L Advance: 879
MDX Sport: 880
MDX Sport Hybrid 3.0L w/Technology Package: 881
MDX Technology: 882
MDX Touring: 883
MDX w/Advance Package: 884
MDX w/Technology Package: 885
MKC Base: 886
MKC Reserve: 887
MKC Select: 888
MKS Base: 889
MKS EcoBoost: 890
MKT Base: 891
MKX Base: 892
MKX Black Label: 893
MKX Reserve: 894
MKZ Base: 895
MKZ Hybrid Base: 896
MKZ Reserve: 897
MKZ Reserve I: 898
MKZ Select: 899
MX-5 Miata Base: 900
MX-5 Miata Club: 901
MX-5 Miata Grand Touring: 902
MX-5 Miata RF Club: 903
MX-5 Miata RF Grand Touring: 904
MX-5 Miata Shinsen: 905
MX-5 Miata Sport: 906
Macan: 907
Macan Base: 908
Macan GTS: 909
Macan S: 910
Macan Turbo: 911
Magnum Base: 912
Magnum R/T: 913
Malibu 1LT: 914
Malibu LT: 915
Malibu LTZ: 916
Malibu Limited LT: 917
Malibu Premier: 918
Marauder Base: 919
Mark LT Base: 920
Martin V8 Vantage Base: 921
Martin Vantage GT Base: 922
Matrix XRS: 923
Maverick Lariat: 924
Maverick XL: 925
Maverick XLT: 926
Maxima 3.5 SR: 927
Maxima GLE: 928
Maxima SL: 929
Maxima SV: 930
Maybach S S 600: 931
Mazda3 FWD w/Preferred Package: 932
Mazda3 FWD w/Premium Package: 933
Mazda3 Grand Touring: 934
Mazda3 Touring: 935
Mazda3 i SV: 936
Mazda3 i Sport: 937
Mazda3 i Touring: 938
Mazda3 s Grand Touring: 939
Mazda3 s Sport: 940
Mazda6 Carbon Edition: 941
Mazda6 Grand Touring: 942
Mazda6 Grand Touring Reserve: 943
Mazda6 Touring: 944
Mazda6 i Grand Touring: 945
Mazda6 i Touring: 946
Mazda6 iSport VE: 947
MazdaSpeed Miata MX-5 Base: 948

In [9]:
# Aplicar Label Encoding a transmission
label_encoder = LabelEncoder()
df['transmission_label'] = label_encoder.fit_transform(df['transmission'])
# Mostrar cómo se asignaron los valores
print("\nAsignación de valores en Label Encoding:")
for clase, valor in zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)):
    print(f"{clase}: {valor}")

Asignación de valores en Label Encoding:
1-Speed Automatic: 0
10-Speed A/T: 1
10-Speed Automatic: 2
2: 3
4-Speed A/T: 4
4-Speed Automatic: 5
5-Speed A/T: 6
5-Speed Automatic: 7
5-Speed M/T: 8
6 Speed At/Mt: 9
6 Speed Mt: 10
6-Speed: 11
6-Speed A/T: 12
6-Speed Automatic: 13
6-Speed Automatic with Auto-Shift: 14
6-Speed Electronically Controlled Automatic with O: 15
6-Speed M/T: 16
6-Speed Manual: 17
7-Speed A/T: 18
7-Speed Automatic: 19
7-Speed Automatic with Auto-Shift: 20
7-Speed M/T: 21
8-SPEED AT: 22
8-Speed A/T: 23
8-Speed Automatic: 24
8-Speed Automatic with Auto-Shift: 25
8-Speed Manual: 26
9-Speed A/T: 27
9-Speed Automatic: 28
A/T: 29
Auto, 6-Spd w/CmdShft: 30
Automatic: 31
Automatic CVT: 32
Automatic, 10-Spd: 33
Automatic, 7-Spd S tronic Dual-Clutch: 34
Automatic, 8-Spd: 35
Automatic, 8-Spd M STEPTRONIC w/Drivelogic, Sport & Manual Modes: 36
Automatic, 8-Spd Sport w/Sport & Manual Modes: 37
Automatic, 9-Spd 9G-Tronic: 38
CVT Transmission: 39
CVT-F: 40
F: 41
M/T: 42
Manual: 43
Manual, 6-Spd: 44
SCHEDULED FOR OR IN PRODUCTION: 45
Transmission Overdrive Switch: 46
Transmission w/Dual Shift Mode: 47
Variable: 48

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

#definimos las caracteristicas y la variable objetivo
x = df[['model_year', 'milage','engine_liters','cylinders','horsepower','fuel_type_label','brand_label','ext_col_label','int_col_label','model_label']]
y = df[['price']]

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train,)

y_pred = model.predict(x_test)

# Calcular Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse}")

# También puedes calcular RMSE (Root Mean Squared Error)
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error (RMSE): {rmse}")

# Calcular R² (esto es lo mismo que rf_model.score())
r2 = r2_score(y_test, y_pred)
print(f"R² Score: {r2}")

Mean Squared Error (MSE): 183182976.88596052
Root Mean Squared Error (RMSE): 13534.510589081547
R² Score: 0.5665051517478128

In [11]:
# Configurar RandomForest para reducir overfitting a ~5%
rf_model = RandomForestRegressor(
    n_estimators=100,           # Reducir árboles
    max_depth=15,               # Limitar profundidad
    min_samples_split=10,       # Más muestras por split
    min_samples_leaf=5,         # Más muestras por hoja
    max_features='sqrt',        # Limitar features por árbol
    random_state=42,
    n_jobs=-1
)

rf_model.fit(x_train, y_train)
y_pred = rf_model.predict(x_test)

# Calcular Mean Squared Error (MSE)
rf_mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error (MSE): {rf_mse}")

# También puedes calcular RMSE (Root Mean Squared Error)
rf_rmse = np.sqrt(rf_mse)
print(f"Root Mean Squared Error (RMSE): {rf_rmse}")

# Calcular R² (esto es lo mismo que rf_model.score())
rf_r2 = r2_score(y_test, y_pred)
print(f"R² Score: {rf_r2}")

d:\proyectos_bootcamp\modulo 3\proyecto-7-Regresion\Problema-de-regresi-n\.venv\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Mean Squared Error (MSE): 89646050.04581557
Root Mean Squared Error (RMSE): 9468.159802507327
R² Score: 0.7878563744205798

In [12]:
pred_df = pd.DataFrame({
    'Actual Value': y_test.values.ravel(),
    'Predicted Value': y_pred.ravel(),
    'Difference': y_test.values.ravel() - y_pred.ravel()
})
pred_df

     Actual Value  Predicted Value    Difference
0         31950.0     25626.267339   6323.732661
1         19290.0     29971.225491 -10681.225491
2         55329.0     47345.837606   7983.162394
3         42995.0     48454.420109  -5459.420109
4         34084.0     34084.319147     -0.319147
..            ...              ...           ...
683       35000.0     18217.614704  16782.385296
684       25500.0     33417.277929  -7917.277929
685       23000.0     17516.261161   5483.738839
686       28000.0     20768.079094   7231.920906
687       60000.0     36369.089071  23630.910929

[688 rows x 3 columns]

In [13]:
# 1. PRIMERO: Obtén predicciones en TRAIN (esto es lo que te falta)
y_train_pred = rf_model.predict(x_train)

# 2. Calcula R² para ambos conjuntos
from sklearn.metrics import r2_score, mean_squared_error

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_pred)

# 3. FÓRMULA PRINCIPAL para detectar overfitting:
diferencia_r2 = r2_train - r2_test
tiene_overfitting = diferencia_r2 > 0.1  # Umbral común

print(f"R² Train: {r2_train:.4f}")
print(f"R² Test: {r2_test:.4f}")
print(f"Overfitting (diferencia R²): {diferencia_r2:.4f} ({diferencia_r2*100:.2f}%)")

R² Train: 0.8690
R² Test: 0.7879
Overfitting (diferencia R²): 0.0812 (8.12%)

In [14]:
# Si error en test es >50% mayor que en train → Overfitting
rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test = np.sqrt(mean_squared_error(y_test, y_pred))
overfitting_rmse = ((rmse_test - rmse_train) / rmse_train) * 100

print(f"Overfitting RMSE: {overfitting_rmse:.2f}%")

Overfitting RMSE: 26.00%